### ISSUE TITLE
The Exporter should include some retries in connecting to ATS Stats URL

### ISSUE THREAD

**Issue by naveen-krishnaprasad** [gdvalle/trafficserver_exporter#3]
In a typical cloud environment, the Traffic server can sometimes be inaccessible, or be brought up after the ATS Exporter container. 

It would be good to have some retries built into the Collector when it comes up to request stats.

**Comment by gdvalle** [comment]
It seems like we'd be a little bit at risk for not representing the rocky connection to Prometheus clearly.  If a scrape connection fails we really want `up == 0` for alert purposes.

I think if we add retry logic to the scraper it'd be prudent to also record a metric for when those retries are made, and maybe default to no retries.

The design I've used in the past for this is to have the exporter running alongside each server, so the ATS scrape having connection problems should really only happen in server down situations.  I've found that to be a reliable setup.

What do you think?

**Comment by gdvalle** [comment]
Added some basic retry logic using `requests` in https://github.com/gdvalle/trafficserver_exporter/pull/9.

I didn't manage to record metrics for each exception there, but the option is at least there now.

Thanks for the suggestion!
